image: devago/docker-compose

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_FILE: docker-compose.yml

# before_script:
#   -

build:
  # variables:
  #   ENV_FILE: .env.stage
  tags:
    - docker
  stage: build
  script:
    - echo $CI_JOB_STAGE
    - docker-compose build --force-rm --no-cache
    - docker-compose push
  # when:
  #   manual

deploy:
  tags:
    - docker
  stage: deploy
  script:
    - echo $CI_JOB_STAGE
    - eval "$(docker-machine env stage)"
    - cp .env.stage .env
    - set -a; [ -f .env.stage ] && . .env; set +a
    - docker-compose down --volumes --remove-orphans --rmi local
    - docker-compose pull
    - docker-compose up --detach --force-recreate
    - echo Welcome to the browser!
    - curl -I 0.0.0.0:8080
  # when:
  #   manual
