version: '3.7'

services:
  app:
    image: go-hello
    container_name: go-hello
    build:
      dockerfile: Dockerfile
      context: ./app/
    ports:
      - "8080:8080"
    healthcheck:
      test: curl -sS http://127.0.0.1:8080 || echo 1
      interval: 5s
      timeout: 10s
      retries: 3
    # restart: on-failure
    # command:
    # environment:
    #   - variable
    # volumes:
    # networks: